#!/usr/bin/env python
# Copyright (c) NTNU, Norwegian University of Science and Technology
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from setuptools import setup, find_packages

setup(name='tpk4170',
      version='0.0.3',
      description='Python modules for the course TPK4170 Robotics at NTNU ',
      author='Lars Tingelstad',
      author_email='lars.tingelstad@ntnu.no',
      url='',
      download_url='https://github.com/tingelst/tpk4170-robotics/archive/master.zip',
      packages=find_packages(),
      install_requires=[
          'numpy>=1.15.0',
          'matplotlib>=3.0.0',
          'pycollada>=0.4.1',
          'pythreejs>=2.0.0',
          'opencv-python>=3.4.4',
          'sympy'
      ],
      data_files=[
          ('share/tpk4170/models/ur5/visual/',
           [
               'tpk4170/models/ur5/visual/base.dae',
               'tpk4170/models/ur5/visual/forearm.dae',
               'tpk4170/models/ur5/visual/shoulder.dae',
               'tpk4170/models/ur5/visual/upperarm.dae',
               'tpk4170/models/ur5/visual/wrist1.dae',
               'tpk4170/models/ur5/visual/wrist2.dae',
               'tpk4170/models/ur5/visual/wrist3.dae',
           ]),
          ('share/tpk4170/models/kr6r900sixx/visual/',
           [
               'tpk4170/models/kr6r900sixx/visual/base_link.dae',
               'tpk4170/models/kr6r900sixx/visual/link_1.dae',
               'tpk4170/models/kr6r900sixx/visual/link_2.dae',
               'tpk4170/models/kr6r900sixx/visual/link_3.dae',
               'tpk4170/models/kr6r900sixx/visual/link_4.dae',
               'tpk4170/models/kr6r900sixx/visual/link_5.dae',
               'tpk4170/models/kr6r900sixx/visual/link_6.dae',
           ]),
          ('share/tpk4170/models/kr16_2/visual/',
           [
               'tpk4170/models/kr16_2/visual/base_link.dae',
               'tpk4170/models/kr16_2/visual/link_1.dae',
               'tpk4170/models/kr16_2/visual/link_2.dae',
               'tpk4170/models/kr16_2/visual/link_3.dae',
               'tpk4170/models/kr16_2/visual/link_4.dae',
               'tpk4170/models/kr16_2/visual/link_5.dae',
               'tpk4170/models/kr16_2/visual/link_6.dae',
           ]),
          ('share/tpk4170/camera_calibration/images',
           [
               'tpk4170/camera_calibration/images/left01.jpg',
               'tpk4170/camera_calibration/images/left02.jpg',
               'tpk4170/camera_calibration/images/left03.jpg',
               'tpk4170/camera_calibration/images/left04.jpg',
               'tpk4170/camera_calibration/images/left05.jpg',
               'tpk4170/camera_calibration/images/left06.jpg',
               'tpk4170/camera_calibration/images/left07.jpg',
               'tpk4170/camera_calibration/images/left08.jpg',
               'tpk4170/camera_calibration/images/left09.jpg',
               'tpk4170/camera_calibration/images/left11.jpg',
               'tpk4170/camera_calibration/images/left12.jpg',
               'tpk4170/camera_calibration/images/left13.jpg',
               'tpk4170/camera_calibration/images/left14.jpg',
           ]),
          ('share/tpk4170/hand_eye_calibration/images',
           [
               'tpk4170/hand_eye_calibration/data/images/image00.png',
               'tpk4170/hand_eye_calibration/data/images/image01.png',
               'tpk4170/hand_eye_calibration/data/images/image02.png',
               'tpk4170/hand_eye_calibration/data/images/image03.png',
               'tpk4170/hand_eye_calibration/data/images/image04.png',
               'tpk4170/hand_eye_calibration/data/images/image05.png',
               'tpk4170/hand_eye_calibration/data/images/image06.png',
               'tpk4170/hand_eye_calibration/data/images/image07.png',
               'tpk4170/hand_eye_calibration/data/images/image08.png',
               'tpk4170/hand_eye_calibration/data/images/image09.png',
               'tpk4170/hand_eye_calibration/data/images/image10.png',
               'tpk4170/hand_eye_calibration/data/images/image11.png',
               'tpk4170/hand_eye_calibration/data/images/image12.png',
               'tpk4170/hand_eye_calibration/data/images/image13.png',
               'tpk4170/hand_eye_calibration/data/images/image14.png',
               'tpk4170/hand_eye_calibration/data/images/image15.png',
               'tpk4170/hand_eye_calibration/data/images/image16.png',
               'tpk4170/hand_eye_calibration/data/images/image17.png',
               'tpk4170/hand_eye_calibration/data/images/image18.png',
               'tpk4170/hand_eye_calibration/data/images/image19.png',
           ]),
          ('share/tpk4170/hand_eye_calibration/poses',
           [
               'tpk4170/hand_eye_calibration/data/poses/pose00.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose01.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose02.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose03.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose04.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose05.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose06.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose07.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose08.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose09.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose10.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose11.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose12.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose13.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose14.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose15.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose16.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose17.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose18.txt',
               'tpk4170/hand_eye_calibration/data/poses/pose19.txt',
           ]),

      ],
      classifiers=[
          "Programming Language :: Python :: 3",
          "License :: OSI Approved :: MIT License",
          "Operating System :: OS Independent",
      ],
      )
